/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./site-model-low.glb -t -k -T -j 
Files: ./site-model-low.glb [927.4KB] > /Users/none/dev/work/adaptaxe/homepage/apps/home/site-model-low-transformed.glb [320.56KB] (65%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Core: THREE.Mesh
    FloydRose: THREE.Mesh
    Humbucker: THREE.Mesh
    LeftBody: THREE.Mesh
    LeftPlateFilled: THREE.Mesh
    LeftPlateSquared: THREE.Mesh
    NeckBlock: THREE.Mesh
    Pickup3Humbucker: THREE.Mesh
    PickupBattery: THREE.Mesh
    RightBodyFilled: THREE.Mesh
    RightBodySquared: THREE.Mesh
    RightPlateFilled: THREE.Mesh
    RightPlateSquared: THREE.Mesh
  }
  materials: {}
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/site-model-low-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh name="Core" geometry={nodes.Core.geometry} material={nodes.Core.material} scale={0.03} />
      <mesh name="FloydRose" geometry={nodes.FloydRose.geometry} material={nodes.FloydRose.material} scale={0.03} />
      <mesh name="Humbucker" geometry={nodes.Humbucker.geometry} material={nodes.Humbucker.material} scale={0.03} />
      <mesh name="LeftBody" geometry={nodes.LeftBody.geometry} material={nodes.LeftBody.material} scale={0.03} />
      <mesh name="LeftPlateFilled" geometry={nodes.LeftPlateFilled.geometry} material={nodes.LeftPlateFilled.material} scale={0.03} />
      <mesh name="LeftPlateSquared" geometry={nodes.LeftPlateSquared.geometry} material={nodes.LeftPlateSquared.material} scale={0.03} />
      <mesh name="NeckBlock" geometry={nodes.NeckBlock.geometry} material={nodes.NeckBlock.material} scale={0.03} />
      <mesh name="Pickup3Humbucker" geometry={nodes.Pickup3Humbucker.geometry} material={nodes.Pickup3Humbucker.material} scale={0.03} />
      <mesh name="PickupBattery" geometry={nodes.PickupBattery.geometry} material={nodes.PickupBattery.material} scale={0.03} />
      <mesh name="RightBodyFilled" geometry={nodes.RightBodyFilled.geometry} material={nodes.RightBodyFilled.material} scale={0.03} />
      <mesh name="RightBodySquared" geometry={nodes.RightBodySquared.geometry} material={nodes.RightBodySquared.material} scale={0.03} />
      <mesh name="RightPlateFilled" geometry={nodes.RightPlateFilled.geometry} material={nodes.RightPlateFilled.material} scale={0.03} />
      <mesh name="RightPlateSquared" geometry={nodes.RightPlateSquared.geometry} material={nodes.RightPlateSquared.material} scale={0.03} />
    </group>
  )
}

useGLTF.preload('/site-model-low-transformed.glb')
